# @generated by https://codeberg.org/goldstein/unflake
let
  indirect_deps = {
  };
  specs = rec {
    unflake_github_denful_den = {
      type = "github";
      owner = "denful";
      repo = "den";
      rev = "36c8ba5c07e2aa7d4816c6314ff2b6656293dee4";
      lastModified = 1788469400;
      narHash = "sha256-2NVetxl+ycFWX4NZTCRqEnx4F37QajVpJe/b+n1Xw9I=";
    };
    unflake_github_denful_with-inputs = {
      type = "github";
      owner = "denful";
      repo = "with-inputs";
      rev = "f0a6bc2464d744e6e3089f89ea6efeb9427c4acd";
      lastModified = 1788467216;
      narHash = "sha256-yFXytpx2/EzFCji5gbn819t9AcIOe5LnlFTnrIkoZ/Q=";
    };
    unflake_github_nix-community_home-manager = {
      type = "github";
      owner = "nix-community";
      repo = "home-manager";
      rev = "693e8ce0fb240a73c116a03cfd7b19269c87af88";
      lastModified = 1788487777;
      narHash = "sha256-Ro/e1N4ZR8/XaFF+sF9SgfPK79HM5YNEppzFj8p+0Ak=";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "9387b3fcc0c23c86661636da63faabad4235a0a6";
      lastModified = 1788372231;
      narHash = "sha256-7aqErvrAEz/5OcPA5p3M+tVOqeYc4oJXkNIPXfCqxAw=";
    };
    unflake_github_denful_with-inputs_flake_false = unflake_github_denful_with-inputs;
  };
  deps = indirect_deps // builtins.mapAttrs (_: spec: builtins.fetchTree spec) specs;
  injections = rec {
    unflake_github_denful_den = {
    };
    unflake_github_nix-community_home-manager = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
    };
  };
  inject = name: flake_path: subdir:
    let
      inputs = builtins.mapAttrs (_: dep: universe.${dep}) injections.${name} // {
        inherit self;
      };
      sourceInfo = deps.${name};
      outPath = "${sourceInfo.outPath}${subdir}";
      outputs = (import "${sourceInfo.outPath}/${flake_path}").outputs inputs;
      self = outputs // sourceInfo // {
        inherit inputs outputs outPath sourceInfo;
        _type = "flake";
        _flake = true;
      };
    in self;
  universe = rec {
    unflake_github_denful_den = inject "unflake_github_denful_den" "flake.nix" "";
    unflake_github_denful_with-inputs_flake_false = deps.unflake_github_denful_with-inputs_flake_false;
    unflake_github_nix-community_home-manager = inject "unflake_github_nix-community_home-manager" "flake.nix" "";
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = inject "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable" "flake.nix" "";
  };
  inputs = {
    den = universe.unflake_github_denful_den;
    home-manager = universe.unflake_github_nix-community_home-manager;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    with-inputs = universe.unflake_github_denful_with-inputs_flake_false;
  };
in inputs // {
  withInputs = fn: let outputs = fn (inputs // { inherit self; }); self = outputs // {
    inherit inputs outputs;
    _type = "flake";
    outPath = builtins.toString ./.;
  }; in self;
  __functor = self: self.withInputs;
  self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
  _unflake = { inherit specs deps injections; };
}
